### ISSUE TITLE
Code review 

### ISSUE THREAD

**Issue by acoustic925** [Dimonix-mw/WebApiHomework7#1]
Добрый день!

**Посмотрев код, заметил несколько моментов:**
1. Использование httpclient через создание new HttpClient() не очень хорошая практика имеющая ряд проблем, причины, почему это плохо можно найти в статьях, скину тут несколько для примера, в целом на просторе интернета их много:
https://www.c-sharpcorner.com/article/httpclientfactory-vs-httpclient-to-implement-api-calls/
https://russianblogs.com/article/83051268582/

2. В проекте ConsoleClient создана папка Repositories, где в виде статического класса расширения, реализована логика отправки сообщений к web-api сервису. 

По этому поводу, на мой взгляд есть несколько замечаний, не очень корректно называть эту папку repositories, т.к. отношения к репозиторию, то что содержится в ней не имеет, более подходящее название infrastructure - обычно так называют и держат в ней интерфейсы и классы, которые относятся к каким-то внешним объектам в виде пары I...Service(интерфейс) и ...Service(реализация), однако при условии, что текущий web-api внутри наших проектов, часто такие реализации называют не ...Service, а ...Adapter, что указывает на принадлежность к внутренней инфраструктуре.

Второе замечание, заключается в том, что обычно статические классы используют в виде Helpers, т.е. вспомогательные классы, которые помогают выполнять мелкие задачки, не относящиеся к БЛ, например могут реализовывать, какие-нибудь математические преобразования. В данном случае статический класс ничего не расширяет и его не имеет смысыл использовать. Лучше всего использовать некую абстракцию, в данном случае реализующую два метода: отправить и запросить customer, и ее реализацию, где внутри вы будете полностью инкапсулировать работу с httpclient, создаваемого через ihttpclientfactory. Вот пример, как можно это сделать:

     public async Task<int> SendCustomer(Customer customer)
        {
            var client = _factory.CreateClient("web-api");
            var customerRequest = new CustomerCreateRequest(customer.Firstname, customer.Lastname);

            var content = new StringContent(JsonConvert.SerializeObject(customerRequest), Encoding.UTF8);
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            var response = await client.PostAsync(client.BaseAddress, content);

            return int.Parse(await response.Content.ReadAsStringAsync());
        }

В остальном все отлично, посмотрел как работать с Dapper, сам никогда не использовал, а тут удобно, живой пример)

**Comment by Dimonix-mw** [comment]
спасибо за замечания, внес изменения по Вашим предложениям. На счет Dapper сам с ним первый раз - решил попробовать с ним
