### ISSUE TITLE
Код-ревью. Предложение

### ISSUE THREAD

**Issue by FedorSharapov** [Dimonix-mw/WebApiHomework7#2]
Здравствуйте, Дмитрий!

Мне понравилась ваша работа и понравилась что вы используете DependencyInjection!
У меня есть незначительное предложение по улучшению, которое немного увеличит производительность.
Т.к. мы от пользователя получаем id в string и в http запрос тоже посылаем в string, то мне кажется, что выгоднее после запроса Id у пользователя в консольном клиенте не преобразовывать в long а просто проверять что это число и передавать в метод тип данных string. Тогда мы уберем дополнительную конвертацию из long в string.

```
public async Task<Customer> GetCustomerByIdAsync(string id)

...
Console.Write("Enter id customer: ");
string customerIdStr = Console.ReadLine();

if (Int64.TryParse(customerIdStr, out customerId))
{
    var customer = await _webApiService.GetCustomerByIdAsync(customerIdStr );
    ...
}
else
     Console.WriteLine("Incorrect id value!");
...

public async Task<string> CreateCustomerAsync(long id)
{
    ...
    if (response.IsSuccessStatusCode)
         var idStr = await response.Content.ReadAsStringAsync();
            
    return id;
 }
```

**Comment by Dimonix-mw** [comment]
Здравствуй - спасибо за предложение.

**Comment by Dejsving** [comment]
проверяя что это число - вы все равно его преобразуете - по другому шарп не умеет, но замечание дельное - я бы предложил вообще проверять на Empty и потом отправлять на сервер запрос - если не long, то прилетит ошибка от сервера
